-- Run in the Supabase SQL Editor using an administrator account, then download
-- the result grid as CSV. Change collection_mode to 'test' for test records.
select
  id as response_id,
  client_submission_id,
  questionnaire_version,
  schema_version,
  submitted_at,
  situation,
  route,
  graduation_year,
  employment_status,
  employment_other,
  array_to_string(industries, ' | ') as industries,
  industry_other,
  cross_cultural_transition,
  ai_expected_impact,
  b1_ratings ->> 'B1_1' as b1_1,
  b1_ratings ->> 'B1_2' as b1_2,
  b1_ratings ->> 'B1_3' as b1_3,
  b1_ratings ->> 'B1_4' as b1_4,
  b1_ratings ->> 'B1_5' as b1_5,
  b1_ratings ->> 'B1_6' as b1_6,
  b1_ratings ->> 'B1_7' as b1_7,
  b1_ratings ->> 'B1_8' as b1_8,
  b1_ratings ->> 'B1_9' as b1_9,
  b1_ratings ->> 'B1_10' as b1_10,
  b1_ratings ->> 'B1_11' as b1_11,
  b1_ratings ->> 'B1_12' as b1_12,
  b1_ratings ->> 'B1_13' as b1_13,
  b1_ratings ->> 'B1_14' as b1_14,
  b1_ratings ->> 'B1_15' as b1_15,
  b2_ratings ->> 'B2_1' as b2_1,
  b2_ratings ->> 'B2_2' as b2_2,
  b2_ratings ->> 'B2_3' as b2_3,
  b2_ratings ->> 'B2_4' as b2_4,
  b2_ratings ->> 'B2_5' as b2_5,
  b2_ratings ->> 'B2_6' as b2_6,
  b2_ratings ->> 'B2_7' as b2_7,
  b2_ratings ->> 'B2_8' as b2_8,
  b2_ratings ->> 'B2_9' as b2_9,
  b2_ratings ->> 'B2_10' as b2_10,
  b2_ratings ->> 'B2_11' as b2_11,
  b2_ratings ->> 'B2_12' as b2_12,
  b2_ratings ->> 'B2_13' as b2_13,
  b2_ratings ->> 'B2_14' as b2_14,
  b2_ratings ->> 'B2_15' as b2_15,
  array_to_string(challenges, ' | ') as challenges,
  challenge_other,
  challenge_explanation,
  array_to_string(reasons, ' | ') as reasons,
  reason_other,
  array_to_string(support_options, ' | ') as support_options,
  support_other,
  support_rank_1,
  support_rank_2,
  support_rank_3,
  d3_ratings ->> 'D3_1' as d3_1,
  d3_ratings ->> 'D3_2' as d3_2,
  d3_ratings ->> 'D3_3' as d3_3,
  d3_ratings ->> 'D3_4' as d3_4,
  d3_ratings ->> 'D3_5' as d3_5,
  d3_ratings ->> 'D3_6' as d3_6,
  d3_ratings ->> 'D3_7' as d3_7,
  d3_ratings ->> 'D3_8' as d3_8,
  d3_ratings ->> 'D3_9' as d3_9,
  useful_support,
  mentoring_support,
  employer_understanding,
  final_comments
from public.aep_questionnaire_responses
where collection_mode = 'live'
order by submitted_at, id;
